# Generated by Django 4.0.3 on 2022-04-24 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCapt', models.BooleanField()),
                ('locationX', models.FloatField()),
                ('locationY', models.FloatField()),
                ('teamName', models.TextField()),
                ('password', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmr', models.IntegerField()),
                ('teamHouseX', models.FloatField()),
                ('teamHouseY', models.FloatField()),
                ('sport', models.TextField()),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.user')),
            ],
        ),
    ]
