# Generated by Django 4.0.3 on 2022-04-28 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='isCapt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='locationX',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='locationY',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='teamName',
            field=models.TextField(default=''),
        ),
    ]
