# Generated by Django 4.0.3 on 2022-05-12 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_team_captain_user_email_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='teamHouseX',
        ),
        migrations.RemoveField(
            model_name='team',
            name='teamHouseY',
        ),
        migrations.RemoveField(
            model_name='user',
            name='locationX',
        ),
        migrations.RemoveField(
            model_name='user',
            name='locationY',
        ),
        migrations.RemoveField(
            model_name='user',
            name='teamName',
        ),
        migrations.AddField(
            model_name='team',
            name='teamAddress',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='team',
            name='teamName',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='teams',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_win', models.BooleanField(default=False)),
                ('opponent_win', models.BooleanField(default=False)),
                ('host_accept', models.BooleanField(default=False)),
                ('opponent_accept', models.BooleanField(default=False)),
                ('match_sport', models.TextField(default='')),
                ('match_time', models.TextField(default='')),
                ('match_status', models.TextField(default='Waiting for both teams to accept')),
                ('host_team', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='host_team', to='website.team')),
                ('opponent_team', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='opponent_team', to='website.team')),
            ],
        ),
    ]
