# Generated by Django 4.0.3 on 2022-05-13 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_team_teamhousex_remove_team_teamhousey_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='host_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='opponent_team',
        ),
    ]
