# Generated by Django 4.0.3 on 2022-05-13 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_match_host_team_remove_match_opponent_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='host_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='host_team', to='website.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='opponent_team', to='website.team'),
        ),
    ]
